--- #YAML:1.0
name:               Prompt-Timeout
version:            1.02
abstract:           prompt() with auto-selecting default value in case of inactivity
author:
    - Serguei Trouchelle <stro@railways.dp.ua>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Term::ReadKey:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
